config/routes.rb
Rails.application.routes.draw do

  resources :cars
  resources :users,
    only: [:new, :create],
    path_names: { new: 'signup' }

  get 'login' => 'sessions#login'
  post 'login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/auth/:provider/callback' => 'sessions#oauth'

  root 'cars#index'

end

app/models/car.rb
class Car < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password(validations: false)

  validates_confirmation_of :password, if: lambda { |m| !m.omniauth? && m.password.present? }
  validates_presence_of :password, on: :create, if: lambda { |m| !m.omniauth? }
  validates_presence_of :password_confirmation, if: lambda { |m| !m.omniauth? && m.password.present? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private
  def current_user
    @user ||= User.find(session[:id]) if session[:id]
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:model, :make, :year, :price)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:id] = user.id
      redirect_to root_path, notice: "Hi #{user.first_name.titlecase}"
    else
      flash[:error] = 'Invalid email or password'
      render :login
    end
  end

  def destroy
    if user = current_user
      session[:id] = nil
      redirect_to root_path, notice: "#{user.first_name} has been logged out"
    end
  end

  def oauth
    @user = User.where(email: omniauth_options[:email]).first_or_initialize(omniauth_options)
    if @user.persisted?
      session[:id] = @user.id
      redirect_to root_path, notice: "Welcome back #{@user.first_name}"
    else
      render 'users/new'
    end
  end

  private

  def omniauth_options
    if auth_hash = request.env['omniauth.auth']
      first_name, last_name = auth_hash[:info][:name].split(/\s+/, 2)
      {
        email: auth_hash[:info][:email],
        first_name: first_name,
        last_name: last_name,
        omniauth: true
      }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:id] = @user.id
        format.html { redirect_to cars_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :omniauth)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @car.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h4>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :model, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :model, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :make, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :make, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :year, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :year, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :price, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :price, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/cars/edit.html.erb
<div class="page-header">
  <%= link_to cars_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @car, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing car</h1>
</div>

<%= render 'form' %>

app/views/cars/index.html.erb
<div class="page-header">
  <%= link_to new_car_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Car
  <% end %>
  <h1>Listing cars</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Model</th>
            <th>Make</th>
            <th>Year</th>
            <th>Price</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @cars) do |car| %>
            <td><%= car.model %></td>
            <td><%= car.make %></td>
            <td><%= car.year %></td>
            <td><%= car.price %></td>
            <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/cars/new.html.erb
<div class="page-header">
  <%= link_to cars_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New car</h1>
</div>

<%= render 'form' %>

app/views/cars/show.html.erb
<div class="page-header">
  <%= link_to cars_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_car_path(@car), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show car</h1>
</div>

<dl class="dl-horizontal">
  <dt>Model:</dt>
  <dd><%= @car.model %></dd>

  <dt>Make:</dt>
  <dd><%= @car.make %></dd>

  <dt>Year:</dt>
  <dd><%= @car.year %></dd>

  <dt>Price:</dt>
  <dd><%= @car.price %></dd>

</dl>

app/views/layouts/_authentication.html.erb
<% if current_user %>
  <li>Signed in as <%= current_user.email %></li>
  <li><%= link_to 'Logout', logout_path, method: :delete, data: { confirm: 'Are you sure you want to logout?'} %></li>
<% else %>
  <li><%= link_to 'Signup', new_user_path %></li>
  <li><%= link_to 'Login', login_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Starter Template for Bootstrap</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Project name", "#", :class => "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <%= render 'layouts/authentication' %>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable" do %>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h4>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :first_name, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :last_name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :last_name, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :email, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, :class => "form-control" %>
    </div>
  </div>

  <% if @user.omniauth %>
    <%= f.hidden_field :omniauth %>
  <% else %>
    <% f.hidden_field :omniauth, value: false %>

    <div class="form-group">
      <%= f.label :password, :class => "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.password_field :password, :class => "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation, :class => "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.password_field :password_confirmation, :class => "form-control" %>
      </div>
    </div>
  <% end %>



  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit 'Signup', :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="page-header">
  <%= link_to users_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @user, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing user</h1>
</div>

<%= render 'form' %>

app/views/users/index.html.erb
<div class="page-header">
  <%= link_to new_user_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New User
  <% end %>
  <h1>Listing users</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>First name</th>
            <th>Last name</th>
            <th>Email</th>
            <th>Password digest</th>
            <th>Omniauth</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @users) do |user| %>
            <td><%= user.first_name %></td>
            <td><%= user.last_name %></td>
            <td><%= user.email %></td>
            <td><%= user.password_digest %></td>
            <td><%= user.omniauth %></td>
            <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<div class="jumbotron">
  <div class="row">
    <% unless @user.omniauth? %>
      <div class="col-xs-6 center-block">
        <%= image_tag('octocat.png', calss: 'img-responsive', size: '40x40') %>
        <%= link_to button_tag('Sign up via Github', class: 'btn btn-primary'), '/auth/github' %>
      </div>
        <div class="col-xs-4 col-xs-offset-2">
          <h1>Signup</h1>
        </div>
    <% else %>
      <div class="col-xs-10 col-xs-offset-2 center-block">
        <h1>Verify Details</h1>
    <% end %>


    <%= render 'users/form' %>

    <%= link_to users_path, :class => 'btn btn-default col-sm-offset-2' do %>
      <span class="glyphicon glyphicon-list-alt"></span>
      Back
    <% end %>

      </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="page-header">
  <%= link_to users_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_user_path(@user), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show user</h1>
</div>

<dl class="dl-horizontal">
  <dt>First name:</dt>
  <dd><%= @user.first_name %></dd>

  <dt>Last name:</dt>
  <dd><%= @user.last_name %></dd>

  <dt>Email:</dt>
  <dd><%= @user.email %></dd>


</dl>